name: CI

on: [push, pull_request]

jobs:
  run-tests:
    name: Lint and run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: npm i
      - run: npm run lint
      - run: npm test
      - run: npm run build
        env:
          CI: true
